version: '3'
services:
  python:
    container_name: chatgpt-python-container
    build:
      context: .
      dockerfile: container/python/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:80" # コンテナの80番ポートをホストの8000番ポートから利用する
  redis:
    container_name: chatgpt-redis-container
    build:
      context: .
      dockerfile: container/redis/Dockerfile
    ports:
      - "6379:6379"