version: '3'
services:
  python:
    container_name: chatgpt-python-container
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - "8000:80" # コンテナの80番ポートをホストの8000番ポートから利用する
  redis:
    container_name: chatgpt-redis-container
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "6379:6379"